"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AdminModal } from "@/components/admin/admin-modal";

type Media = { id: string; filename: string; altText: string; focalPointX: number | null; focalPointY: number | null; mimeType: string; byteSize: number; brandLogos: { id: string; name: string; group: "CLIENT" | "PARTNER" }[] };

function MediaCard({ item, onChange }: { item: Media; onChange: (next: Media) => void }) {
  async function updateFocal(axis: "focalPointX" | "focalPointY", value: number) { const next = { focalPointX: item.focalPointX ?? 50, focalPointY: item.focalPointY ?? 50, altText: item.altText, [axis]: value }; onChange({ ...item, ...next }); await fetch(`/api/admin/media/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(next) }); }
  return <article className="pv-admin-media-card"><div className="pv-admin-media-preview"><img src={`/api/media/${item.id}`} alt={item.altText} style={{ objectPosition: `${item.focalPointX ?? 50}% ${item.focalPointY ?? 50}%` }} /></div><div className="pv-admin-media-details"><strong>{item.brandLogos[0]?.name || item.filename}</strong><small>{item.altText}</small><span>{Math.round(item.byteSize / 1024)} KB · {item.mimeType}</span><label className="pv-media-range">Foco horizontal <input type="range" min="0" max="100" value={item.focalPointX ?? 50} onChange={(event) => updateFocal("focalPointX", Number(event.target.value))} /></label><label className="pv-media-range">Foco vertical <input type="range" min="0" max="100" value={item.focalPointY ?? 50} onChange={(event) => updateFocal("focalPointY", Number(event.target.value))} /></label></div></article>;
}

function MediaSection({ title, description, items, onChange }: { title: string; description: string; items: Media[]; onChange: (next: Media) => void }) {
  return <section className="pv-admin-media-section"><header><div><p className="pv-admin-eyebrow">Biblioteca de marca</p><h2>{title}</h2><span>{description}</span></div><strong>{items.length.toString().padStart(2, "0")}</strong></header>{items.length ? <div className="pv-admin-media-grid">{items.map((item) => <MediaCard key={item.id} item={item} onChange={onChange} />)}</div> : <p className="pv-admin-media-empty">Nenhuma logo cadastrada nesta categoria.</p>}</section>;
}

export default function MediaPage() {
  const [items, setItems] = useState<Media[]>([]); const [file, setFile] = useState<File | null>(null); const [altText, setAltText] = useState(""); const [uploadOpen, setUploadOpen] = useState(false); const [error, setError] = useState("");
  function load() { fetch("/api/admin/media").then((response) => response.json()).then((result) => setItems(result.data ?? [])).catch(() => setError("Não foi possível carregar a mídia.")); }
  useEffect(load, []);
  async function upload(event: React.FormEvent) { event.preventDefault(); if (!file) return; const form = new FormData(); form.set("file", file); form.set("altText", altText); const response = await fetch("/api/admin/media", { method: "POST", body: form }); const result = await response.json(); if (!response.ok) setError(result.message); else { setFile(null); setAltText(""); setUploadOpen(false); load(); } }
  function updateItem(next: Media) { setItems((current) => current.map((item) => item.id === next.id ? next : item)); }
  const partnerItems = items.filter((item) => item.brandLogos.some((logo) => logo.group === "PARTNER")); const clientItems = items.filter((item) => item.brandLogos.some((logo) => logo.group === "CLIENT")); const otherItems = items.filter((item) => item.brandLogos.length === 0);
  return <main className="pv-admin-subpage"><header className="pv-admin-subpage-header"><div><Link className="pv-admin-back" href="/admin">← Voltar para visão geral</Link><p className="pv-admin-eyebrow">Biblioteca</p><h1>Mídia</h1><span>Organize as logos por contexto e mantenha as imagens editoriais separadas da marca.</span></div><button className="pv-admin-primary-action" onClick={() => { setError(""); setUploadOpen(true); }}>Enviar imagem <b>↗</b></button></header>{error ? <p className="pv-admin-error">{error}</p> : null}<div className="pv-admin-media-groups"><MediaSection title="Parceiros" description="Logos exibidas na seção de parceiros do site." items={partnerItems} onChange={updateItem} /><MediaSection title="Clientes" description="Logos exibidas na seção de clientes do site." items={clientItems} onChange={updateItem} />{otherItems.length ? <MediaSection title="Outras imagens" description="Arquivos disponíveis para posts e conteúdos editoriais." items={otherItems} onChange={updateItem} /> : null}</div><AdminModal open={uploadOpen} title="Enviar imagem" description="Adicione uma imagem à biblioteca editorial do CMS." onClose={() => setUploadOpen(false)}><form className="pv-admin-upload-form" onSubmit={upload}><label className="pv-admin-modal-field">Arquivo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)} required /></label><label className="pv-admin-modal-field">Texto alternativo<input value={altText} onChange={(event) => setAltText(event.target.value)} placeholder="Descreva a imagem" required /></label><button className="pv-admin-primary-action">Enviar imagem <b>↗</b></button></form></AdminModal></main>;
}
